version: "3.8"
services:
  first-node:
    image: blockchain_node
    container_name: node_0
    command: java -jar /app/blockchain.jar -n node_0 -g
    ports:
      - "9020:9020"
  second-node:
    image: blockchain_node
    container_name: node_1
    command: java -jar /app/blockchain.jar -n node_1
    ports:
      - "9021:9021"
  third-node:
    image: blockchain_node
    container_name: node_2
    command: java -jar /app/blockchain.jar -n node_2
    ports:
      - "9022:9022"